<a href="https://colab.research.google.com/github/snehalnandi/React-Data-Dashboard/blob/main/03_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np

# A messy inventory list where some quantities are missing (NaN)
messy_data = {
    'Item': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [50000, 800, 1500, 12000],
    'Stock_Quantity': [10, np.nan, 15, np.nan]
}

inventory_df = pd.DataFrame(messy_data)
print(inventory_df)

       Item  Price  Stock_Quantity
0    Laptop  50000            10.0
1     Mouse    800             NaN
2  Keyboard   1500            15.0
3   Monitor  12000             NaN

In [38]:
# We tell Pandas: take the column, fill the holes with 0, and save it back!
inventory_df['Stock_Quantity'] = inventory_df['Stock_Quantity'].fillna(0)

# Print the fixed table
inventory_df

       Item  Price  Stock_Quantity
0    Laptop  50000            10.0
1     Mouse    800             0.0
2  Keyboard   1500            15.0
3   Monitor  12000             0.0

In [39]:
reorder_items = inventory_df[ (inventory_df['Price'] > 1000) & (inventory_df['Stock_Quantity'] == 0) ]

print(reorder_items)

      Item  Price  Stock_Quantity
3  Monitor  12000             0.0

In [40]:
inventory_df['Total_Value'] = inventory_df['Price'] * inventory_df['Stock_Quantity']
inventory_df

       Item  Price  Stock_Quantity  Total_Value
0    Laptop  50000            10.0     500000.0
1     Mouse    800             0.0          0.0
2  Keyboard   1500            15.0      22500.0
3   Monitor  12000             0.0          0.0

In [41]:
inventory_df.to_csv('my_clean_inventory.csv', index=False)

In [42]:
import pandas as pd
import numpy as np

cafe_data = {
    'Drink': ['Espresso', 'Cappuccino', 'Latte', 'Cold Brew', 'Mocha'],
    'Price': [100, 150, 180, 200, 220],
    'Cups_Sold': [50, np.nan, 30, np.nan, 40]
}

cafe_df = pd.DataFrame(cafe_data)

cafe_df

        Drink  Price  Cups_Sold
0    Espresso    100       50.0
1  Cappuccino    150        NaN
2       Latte    180       30.0
3   Cold Brew    200        NaN
4       Mocha    220       40.0

In [43]:
cafe_df['Cups_Sold'] = cafe_df['Cups_Sold'].fillna(0)
cafe_df

        Drink  Price  Cups_Sold
0    Espresso    100       50.0
1  Cappuccino    150        0.0
2       Latte    180       30.0
3   Cold Brew    200        0.0
4       Mocha    220       40.0

In [44]:
cafe_df['Total_Revenue'] = cafe_df['Price'] * cafe_df['Cups_Sold']
cafe_df

        Drink  Price  Cups_Sold  Total_Revenue
0    Espresso    100       50.0         5000.0
1  Cappuccino    150        0.0            0.0
2       Latte    180       30.0         5400.0
3   Cold Brew    200        0.0            0.0
4       Mocha    220       40.0         8800.0

In [45]:
Start_Drink = cafe_df [(cafe_df['Total_Revenue']>4000)&(cafe_df['Cups_Sold']>35)]
Start_Drink

      Drink  Price  Cups_Sold  Total_Revenue
0  Espresso    100       50.0         5000.0
4     Mocha    220       40.0         8800.0

In [46]:
cafe_df.to_csv('star_drinks_report.csv',index=False)

In [47]:
Start_Drink.to_csv('star_drinks_report.csv',index=False)

In [48]:
Start_Drink

      Drink  Price  Cups_Sold  Total_Revenue
0  Espresso    100       50.0         5000.0
4     Mocha    220       40.0         8800.0